apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: v1
kind: Namespace
metadata:
  name: memcached
---
apiVersion: v1
kind: Namespace
metadata:
  name: cassandra
---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres