apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - name: analytics
        image: dev/analytics:dev
        env:
        - name: KAFKA_ADDRESS
          value: kafka-service.kv-mall-infra:9092
        - name: MEMCACHED_ADDR
          value: memcached.kv-mall-infra:11211
        - name: CASSANDRA_ADDR
          value: cassandra.kv-mall-infra:9042
        - name: POSTGRESQL_ADDR
          value: postgresql://postgres:postgres@postgres.kv-mall-infra:5432/postgres?sslmode=disable
        - name: COSMOS_KEY
          valueFrom:
            secretKeyRef:
              name: cosmos
              key: COSMOS_KEY
        startupProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 100
        ports:
          - name: http
            containerPort: 8081
            protocol: TCP
