apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
  namespace: kv-mall-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/tmp-default: "true"
        io.kompose.service: kafka
    spec:
      serviceAccountName: kv-mall-infra
      containers:
        - env:
            - name: CUSTOM_INIT_SCRIPT
              value: |-
                echo -e 'KafkaServer {\norg.apache.kafka.common.security.scram.ScramLoginModule required\n username="adminscram"\n password="admin-secret";\n org.apache.kafka.common.security.plain.PlainLoginModule required\n username="adminplain"\n password="admin-secret"\n user_adminplain="admin-secret";\n  };' > /opt/kafka/config/kafka_server_jaas.conf;
                /opt/kafka/bin/kafka-configs.sh --zookeeper zookeeper:2181 --alter --add-config 'SCRAM-SHA-256=[password=admin-secret-256],SCRAM-SHA-512=[password=admin-secret-512]' --entity-type users --entity-name adminscram
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: localhost
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-service.kv-mall-infra:9092,SASL_PLAINTEXT://kafka-service.kv-mall-infra:9093
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND
              value: "true"
            - name: KAFKA_AUTHORIZER_CLASS_NAME
              value: kafka.security.auth.SimpleAclAuthorizer
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CREATE_TOPICS
              value: test-writer-0:3:1,test-writer-1:3:1
            - name: KAFKA_DELETE_TOPIC_ENABLE
              value: "true"
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092,SASL_PLAINTEXT://:9093
            - name: KAFKA_MESSAGE_MAX_BYTES
              value: "200000000"
            - name: KAFKA_OPTS
              value: -Djava.security.auth.login.config=/opt/kafka/config/kafka_server_jaas.conf
            - name: KAFKA_SASL_ENABLED_MECHANISMS
              value: PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
            - name: KAFKA_VERSION
              value: 2.3.1
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          image: wurstmeister/kafka:2.12-2.3.1
          name: kafka
          ports:
            - containerPort: 9092
            - containerPort: 9093
          resources: {}
      restartPolicy: Always
status: {}
