apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - name: analytics
        image: keyval/kv-mall-analytics:v0.2
        env:
        - name: KAFKA_ADDRESS
          value: kafka-service.kv-mall-infra:9092
        - name: MEMCACHED_ADDR
          value: memcached.kv-mall-infra:11211
        - name: CASSANDRA_ADDR
          value: cassandra.kv-mall-infra:9042
        - name: POSTGRESQL_ADDR
          value: postgresql://postgres:postgres@postgres.kv-mall-infra:5432/postgres?sslmode=disable
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon
  labels:
    app: coupon
spec:
  selector:
    matchLabels:
      app: coupon
  template:
    metadata:
      labels:
        app: coupon
    spec:
      containers:
      - name: coupon
        image: keyval/kv-mall-coupon:v0.2
        env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: OTEL_TRACES_EXPORTER
            value: otlp
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://$(NODE_IP):4318"
          - name: OTEL_SERVICE_NAME
            value: coupon
          - name: MEMBERSHIP_SERVICE_URL
            value: "membership:8080"
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: coupon
spec:
  selector:
    app: coupon
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: keyval/kv-mall-frontend:v0.2
        env:
        - name: INVENTORY_SERVICE_HOST
          value: inventory:8080
        - name: PRICING_SERVICE_HOST
          value: pricing:8080
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: keyval/kv-mall-inventory:v0.2
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: inventory
spec:
  selector:
    app: inventory
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  labels:
    app: load-generator
spec:
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: load-generator
        image: keyval/kv-mall-load-generator:v0.2
        env:
        - name: BUY_PRODUCT_INTERVAL
          value: "2s"
        - name: GET_PRODUCTS_INTERVAL
          value: "10s"
---
kind: Service
apiVersion: v1
metadata:
  name: load-generator
spec:
  selector:
    app: load-generator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: membership
  labels:
    app: membership
spec:
  selector:
    matchLabels:
      app: membership
  template:
    metadata:
      labels:
        app: membership
    spec:
      containers:
      - name: membership
        image: keyval/kv-mall-membership:v0.2
        env:
          - name: KAFKA_ADDRESS
            value: kafka-service.kv-mall-infra:9092
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: membership
spec:
  selector:
    app: membership
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing
  labels:
    app: pricing
spec:
  selector:
    matchLabels:
      app: pricing
  template:
    metadata:
      labels:
        app: pricing
    spec:
      containers:
      - name: pricing
        image: keyval/kv-mall-pricing:v0.2
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: pricing
spec:
  selector:
    app: pricing
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse
  labels:
    app: warehouse
spec:
  selector:
    matchLabels:
      app: warehouse
  template:
    metadata:
      labels:
        app: warehouse
    spec:
      containers:
      - name: warehouse
        image: dev/warehouse:dev
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: warehouse
spec:
  selector:
    app: warehouse
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080