apiVersion: v1
kind: Namespace
metadata:
  name: kv-mall
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: kv-mall
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          # !! need to bump tag to include currency change from ILS to EUR
          image: registry.odigos.io/kv-mall-frontend:v0.5
          env:
            - name: INVENTORY_SERVICE_HOST
              value: inventory:8080
            - name: PRICING_SERVICE_HOST
              value: pricing:8080
            - name: COUPON_SERVICE_HOST
              value: coupon:8080
            - name: ADS_SERVICE_HOST
              value: ads:8080
            - name: CURRENCY_SERVICE_HOST
              value: currency:8080
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: kv-mall
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

