apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  labels:
    app: load-generator
spec:
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: load-generator
        image: dev/load-generator:dev
        env:
        - name: BUY_PRODUCT_INTERVAL
          value: "2s"
        - name: GET_PRODUCTS_INTERVAL
          value: "10s"
  